FIREBASE_API_KEY="AIzaSyAEIgrHYW7PN7CUL_UbY2_j7B3eKbz4IyA"
FIREBASE_AUTH_DOMAIN="candiatescr.firebaseapp.com"
FIREBASE_PROJECT_ID="candiatescr"
FIREBASE_STORAGE_BUCKET="candiatescr.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID="138935958169"
FIREBASE_APP_ID="1:138935958169:web:ffd35ce08a4a7520c41608"
FIREBASE_MEASUREMENT_ID="G-LEGELTNFN9"

FIREBASE_SERVICE_ACCOUNT_KEY="""
{
  "type": "service_account",
  "project_id": "candiatescr",
  "private_key_id": "023e748ac6a36eeb858faaec7c4def93d360651c",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6eiqlvVjEjnBd\nECGllcLdNVIBDZad0W6k6Swh9glsILMXDGa71K/EckCAQO9Eln/PLC9U6MKZ//zv\n4RQNAk7AasEcY8K+9aBNUBFASlnb27f8MYeSb4YJKJI+YdEVX941VBGFX4kPcukT\nFVeMTesRPzmPTDAWsf2PiQ9haNBR83lNBnxqOt1Uk6APDNKa/T7rjxocERsmkXpH\nuesIo8vesxrs3xB1jmYIQqavwDxTV6QtngSnEZLyXlRvDtI2NPB39cMsMvoC30dl\nbYCvVQAR6gjPOikXpulS6CRE8XEb0zALCelFhPKR2HcwPNL/khp8qA13iD6QdVLU\nO8mzQsWXAgMBAAECggEARmD+QJBedMynhtAkSsjjgzZxDTmyKz0Ua8QfJnAj7T3I\nKb5B9ckXT2aphl47j6DXevrboEm6zIGLVoOV3DUPQNrpqEvUf9rXVeaOpDuLf4mE\n/nc5CiDyLvmzfDzRuyX0CR+B/1rnsT92zP+Ei80Kl3dLw5QHIEGsB6S8e9ChsxOy\nm9nHc0HASGn6DeUyxWNMA/ToMO++tmjIajJaV0BuPC4shfZJmkjdr+DFjhiaMOsb\nmTxshipZ/otugSsQ8IzSdLvciKuITzmsACWTc/AzPTgpJHIHnonvuo/zWUmI/84f\nFpEFQuRvoVRYgeGemtNXULKVU/+pYQbEsFYhftFMeQKBgQDjDOzMwnPrMZYEzRpg\n9G8feQ+EQfVqBjBYHC2L3NVkPA+ow+VFbopu5YOwzDOPbUxBf/rb8Ratn92CW9I2\nPkPk8ZyeA2mgvasK9KgNyr7W8qNzFsBRcBINWKzCeQ0qenv1x0bAlrxR/MMrf0ik\nKOUgDlIF+PIHtZN87EqKdncAvwKBgQDSQOdTVXED5+Es8xP8fmwztbOBEitNnuw3\nrBoTxqynZRKrUOmxb73PCvUDfXIqkSwMtACXF3+N3yodGcROToVmkTevr/yeAwWO\nPjIUmuNuZ8R/iNK6EEE5WWhuUpOMe8TwFGkMlWipoW+hpRoUTqBpeDyetglbvXtR\nQqqa/B8ZKQKBgDY1XMgaWRC7OwUUbwrc8TcDcVfzY4OXzK0MtTciV3Rh/p8dfjzQ\ngo6tj36Dkn/Y6Y7t3lfqvK5hb8Jy58J5pT4hDXKQgASXpCGuff0k/eFV9v5AXVRU\nPIshM8YOnr0Yl0X7+QF8O6QbhAF7lz1SYjoAEUdJw4dhq7/0rmtWk10DAoGAf979\nUU9bhpaV+jJz61IwGFrfqxYTxAdtfoZq7bAc/UmZSxvQpRtigvMVBGRc9MqJ0cf/\nu+SMrQoWoNA09bMHqtOS3ITZzHfl/xaQerugqlrtxOq/zm1oXaqkusP5/Kyhn6mq\nIf8UQmZucA7rh4IySTLZG2V215ar00YKYGwJtdECgYEAymDQMtwQtpLufMj7oONv\nqsiDfv83pgQBiA677XiMEtzR4K1ecTEw9z0Z0tMd82Igfj9COUHn0J9V4POnA+Fh\ng7FBVRvt4Xd6PhJboiEq8P2fu+lKz2bCCPP7X+JMVYrhDplys6PJnBIqJtdjPWrb\nYemsY8Dh9Rid68erJ9ijg6E=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-fbsvc@candiatescr.iam.gserviceaccount.com",
  "client_id": "102317870947004450141",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40candiatescr.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

# Gmail credentials (already present in your code)
GMAIL_ADDRESS = "screenerpro.ai@gmail.com"
GMAIL_APP_PASSWORD = "udwi life nbdv kgdt"
