{
  "type": "service_account",
  "project_id": "candiatescr",
  "private_key_id": "1b9e84fb5240a36143544d86d651188108af403d",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCc2IlK/oq47UM\nDZGg3lA/nt8K0rliXXBfGoQ/xrVDyTBj62Ib3C6QMh2ywR+LFitF4stlC5UwdF/5\nU8lvzx6AtXNeIv1z4RBQ6LQr4KAaxXFQxGPF/7s+Ar2okh9HrE8QNFs5BNShUzGB\nsET+xq7afCA5QoRhlk5Ujxhe6vcf3Z+Irwgm7hk6siU8PUDwJWwJp06pg70jnOLS\nSojx4dMQvdDsU4ZPMlEOLUVcVdI8ewOr6b3DV5py0if2vnXXmBQPexeN38hV7/SP\nCQ0QwP0iBZQTND0m97+LTjhdsvv3vKf85UPfCwM1dX0sTT3QOCAKKo2KwvkJLMUy\n+NAilq3LAgMBAAECggEADRUo8Un4LD04cnXR6no1TqfTEdiuUwk+Wj0Ke3qpuhnQ\ngP3WkqafFgyJJacLXEGYP7zL5SHWXnWLT4HCTRzToeKTadio0iG+W0iMzAxHjrA3\nY4ZoasCTSc9yuzi5lLTpzN6jlJPX9SgHw1X8uQzdDs4dzOcbc7ANLRtDjyn33n4z\nQWhahHm36gNxAzyuChFBd+QolbrLPNctQFAZODFixFM0qd++c6i287EsdeBt7ABd\nmf3oHm2tnQrARprUPv5RC/vDu71Xhk0cDeea2VHODnH1O1QVYt1n/m4kBqb6vpFl\n+JcTNvpthAQWRBEoegqq+2uSQxVp5lnCu/9IHPi4oQKBgQD0Vlysj3WIzyqFx7lN\n4s7ZmAuHKtCQpDzz+kDWB+yrVkJ/2O04RmnTvy0cpSJxRhBb9dU2C94oe5FnczYE\nqb6qZdPiv12whMyld/MJ49oLORqXQjchiuiV6CflrjwdyOpXj20iwswkR4PPKF3X\nnRcSF7nCB4YS5+6ZF34+hQtY5wKBgQDLu3C1G9S9GiFXYmFZilJDkn3LGd5kBdpu\ncqC3nnwk16D1b2sV3kFVB+31XpcYtmtWD11AeoZLBlO3/0niBEkJsZRVlJ6LuQav\nSuTjxSH4AsXFeEavS2ObhOmlAViYp6cWVLbYEcbugIvARorjMDy1WCp8Kp7YSXBt\nQ2Itge/zfQKBgQCAHfiiEucSQW6Oj1c+27qSpgMFcRHDhhrf40yz7ZvPi397AggB\nBgrfmNLSvlP9CTvyvEh7+mUW3RQ1JlggwdDUEGi18JnzwO59pROvD+Z5FAw5W+ME\nl421bPHeoSmshHk8SFx1aacZLtaSfRwXvqsmNYKVltRafXrCk2sC5Ug56QKBgDPb\nBMgESnTLdtsQHmk1DNVILx6H+hQJbVyZbpDuFPknrT9rWZ1aUdS7zPScW+cdX1qr\nVHf5976W4K4/m2Wc455FBdV2m5hCwxHRBUt4PLossnwdrhgmHzdRcErgedV5Ls0/\nSL7cX38LVwbcrbM/7uPVihLKol2465XUBeRBY3rdAoGAaNYCofTDAAvEm81iURMt\nJIXgx6/Fv+3XxoJJuCKYC5bF/KrVXKVtakXc9Y76l/kuAk7basKGkLqTBYbbw2sP\napoDBmcShgH535H1fVid4lc5NOi1gZO9MioMTww/suyAuZ5qNRsSyq4vb3W2db/o\nEwWaBNFFd9jzgxy6nUu4hv4=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-fbsvc@candiatescr.iam.gserviceaccount.com",
  "client_id": "102317870947004450141",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40candiatescr.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
const firebaseConfig = {
  apiKey: "AIzaSyAEIgrHYW7PN7CUL_UbY2_j7B3eKbz4IyA",
  authDomain: "candiatescr.firebaseapp.com",
  projectId: "candiatescr",
  storageBucket: "candiatescr.firebasestorage.app",
  messagingSenderId: "138935958169",
  appId: "1:138935958169:web:ffd35ce08a4a7520c41608",
  measurementId: "G-LEGELTNFN9"
};

GMAIL_ADDRESS = "screenerpro.ai@gmail.com"
GMAIL_APP_PASSWORD = "udwi life nbdv kgdt"
